services:
  - type: web
    name: eduprado-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: https://eduprado.me
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_DIR
        value: /opt/render/project/src/public/images/blog 