services:
  - type: web
    name: eduprado-backend
    env: node
    rootDir: backend
    buildCommand: |
      npm install
      mkdir -p /data/images/blog
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_DIR
        value: /data/images/blog
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 