-- Criar tabela de posts
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    image_url VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Criar índice para melhorar performance de busca
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);

-- Habilitar Row Level Security (RLS)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Criar política para permitir leitura pública
CREATE POLICY "Permitir leitura pública dos posts" ON posts
    FOR SELECT
    USING (true);

-- Criar política para permitir inserção apenas com autenticação
CREATE POLICY "Permitir inserção apenas com autenticação" ON posts
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Criar política para permitir atualização apenas com autenticação
CREATE POLICY "Permitir atualização apenas com autenticação" ON posts
    FOR UPDATE
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

-- Criar política para permitir deleção apenas com autenticação
CREATE POLICY "Permitir deleção apenas com autenticação" ON posts
    FOR DELETE
    USING (auth.role() = 'authenticated'); 